M48
; DRILL file {KiCad (6.0.10-0)} date Wednesday, January 04, 2023 at 02:52:49 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-04T14:52:49-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X74.752Y-50.932
X74.752Y-130.932
X224.752Y-50.932
X224.752Y-130.932
T0
M30
